[Language]
;自动判断系统是否为中文版 1, 自动判断
AutoLanguage=0
;system version 1,中文 2，英文，3，德文 4，西班牙文 5，葡萄牙文 6，阿拉伯文 7， 俄文
Version=1
Language=LedEN.ini
[Config]
LastListName=E:\Sigma系列\Sigma Play\trunk\ImageList.pls
LastFileList=E:\工作空间\NewLedSoft\0706\MyLists\NewList4.fls
RetryNum=3
HalfBrIsValid=0
Version=2
SubWidth=65534
SubHeight=65534
ReturnFlag=0
Priority=0
BroadCast254=1
ProtocolType=240
WithBlack=0
ListenFile=
CheckFile=0
CheckFileTime=1000
CbxSelSignEnabled=0
BeepCount=3
BeepOnOFF=1
BeepStyle=0
BeepDur=3
WinPosX=0
WinPosY=0
CRCSupport=1
FileCRCSupport=1
FixedBaud=0
CustomPort=9522
PixelPer=0
OpenDoor=0
TimesBlack=0
BlackStart=0
CheckTime=1
SendPlaylistDelay=0
[Customize]
Celsius=1
[BrBlock]
Width=128
Height=48
DimStyle=0
[Communicate]
Trans=0
Com1=1
Com2=0
Com3=0
Com4=0
StartIP=169.254.15.00
EndIP=169.254.16.00
StartGroup=01
StartUnit=01
EndUnit=04
DialNum=805
[LogoSet]
LogX=0
LogY=0
LogWidth=128
LogHeight=64
LogValid=1
[LastFile]
InfoFile=
[Connect]
EthernetSel=1
IP=192.168.11.6
Comm=COM9
GroupAddr=1
UnitAddr=1
Port=9520
ProtocolVer=9985
DialBaud=19200
DefaultBaudRate=115200
DefaultBaud=19200
FileSystemVer=1025
FixedPort=0
RetryNum=3
ReadTimeOut=3000
UseCustomTime=1
IntervalTime485=300
ISDNS=0
DNS=
[InitFileDir]
InitFileDir0=C:\MessageFiles
InitFileDir1=C:\Documents and Settings\Administrator\桌面\测试\
InitFileDir2=C:\Documents and Settings\Administrator\桌面\LOGO12345678901234.bmp
[Update]
LastCpuFile=C:\Documents and Settings\Administrator\桌面\ARM-02-8753-02.cpu
LastFpgaFile=G:\配置文件\FPGA5246\fpga_qs5246_ver460C.pga
LastPalette=E:\工作空间\Sigma系列\SigmaPlayer\0713\UPDATE\COLORTY.BIN
LastRDataFile=E:\工作空间\Sigma系列\SigmaPlayer\0713\UPDATE\GammaFile.r
LastBrDataFile=
LastFontList=E:\工作空间\Sigma系列\SigmaPlayer\2010-03-30(4.2.8)\FONT\FontList.fst
LastConfigue=
LastUpdate=C:\Users\user\Desktop\ARM_02_A514_07.cpu
CpuFileEnabled=0
FpgaFileEnabled=1
PaletteEnabled=0
RDataFileEnabled=0
BrDataFileEnabled=0
FontListEnabled=0
ConfigueEnabled=0
FormatCEnabled=0
BackRecoverEnabled=1
BKConfigEnabled=0
FormatDEnabled=0
FormatFEnabled=0
[LogSet]
LogX=0
LogY=0
LogWidth=32
LogHeight=32
LogValid=1
LogTransparent=1
LogFileName=E:\svn_shareFile\Sigma系列\SigmaPlay\branches\Sigma Multi Language\NewLogo.Log
[Dial]
DialNum=805
Comm=COM1
BaudRate=9600
[EMAIL]
SenderName=customer
ReceiverName=Example Server
SendAddr=example@sina.com
RecvAddr=Service@example.com
LogUser=example
Password=qsimage12345678
EmailHost=SMTP.sina.com.cn
SubJect=Sigma Information
BodyStr=Sigma Information From Customer
[UserManage]
Remember=1
[OffsetSet]
PCName=NORMAL PC
PosX=0
PosY=0
[ShutDown]
ListenCom=COM1
BaudRate=19200
Enabled=0
[VideoMonitor]
Address=http://169.254.12.18
[Check]
CheckFiles=1
IgnoreFiles=1
ConnectSign=1
[LeftView]
LeftView0=1
LeftView1=1
LeftView2=1
LeftView3=0
LeftView4=1
LeftView5=1
LeftView6=1
LeftView7=1
LeftView8=0
LeftView9=1
LeftView10=0
LeftView11=0
[SchduleSend]
IsActive=0
GRecordToFile=1
BeginTime=6:03:00 AM
EndTIme=11:59:00 PM
Interval=1
SSText=1
SSPicture=1
SSVideo=0
AutoRun=1
ViewSel=2
LastStartTime=5/2/2026 1:21:38 PM
SignIndex=0
